# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/auth.proto\x12\x04user\".\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\" \n\x0fReadUserRequest\x12\r\n\x05token\x18\x01 \x01(\t\",\n\x10ReadUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\".\n\x0cLoginRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t2z\n\x0b\x41uthService\x12\x39\n\x08ReadUser\x12\x15.user.ReadUserRequest\x1a\x16.user.ReadUserResponse\x12\x30\n\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=27
  _globals['_USER']._serialized_end=73
  _globals['_READUSERREQUEST']._serialized_start=75
  _globals['_READUSERREQUEST']._serialized_end=107
  _globals['_READUSERRESPONSE']._serialized_start=109
  _globals['_READUSERRESPONSE']._serialized_end=153
  _globals['_LOGINREQUEST']._serialized_start=155
  _globals['_LOGINREQUEST']._serialized_end=201
  _globals['_LOGINRESPONSE']._serialized_start=203
  _globals['_LOGINRESPONSE']._serialized_end=233
  _globals['_AUTHSERVICE']._serialized_start=235
  _globals['_AUTHSERVICE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
