# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import planner_pb2 as protos_dot_planner__pb2


class PlannerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadPlans = channel.unary_unary(
            "/planner.PlannerService/ReadPlans",
            request_serializer=protos_dot_planner__pb2.ReadUserPlanRequest.SerializeToString,
            response_deserializer=protos_dot_planner__pb2.ReadUserPlanResponse.FromString,
        )
        self.CreatePlan = channel.unary_unary(
            "/planner.PlannerService/CreatePlan",
            request_serializer=protos_dot_planner__pb2.CreateUserPlanRequest.SerializeToString,
            response_deserializer=protos_dot_planner__pb2.CreateUserPlanResponse.FromString,
        )


class PlannerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadPlans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreatePlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PlannerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ReadPlans": grpc.unary_unary_rpc_method_handler(
            servicer.ReadPlans,
            request_deserializer=protos_dot_planner__pb2.ReadUserPlanRequest.FromString,
            response_serializer=protos_dot_planner__pb2.ReadUserPlanResponse.SerializeToString,
        ),
        "CreatePlan": grpc.unary_unary_rpc_method_handler(
            servicer.CreatePlan,
            request_deserializer=protos_dot_planner__pb2.CreateUserPlanRequest.FromString,
            response_serializer=protos_dot_planner__pb2.CreateUserPlanResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "planner.PlannerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class PlannerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadPlans(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/planner.PlannerService/ReadPlans",
            protos_dot_planner__pb2.ReadUserPlanRequest.SerializeToString,
            protos_dot_planner__pb2.ReadUserPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CreatePlan(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/planner.PlannerService/CreatePlan",
            protos_dot_planner__pb2.CreateUserPlanRequest.SerializeToString,
            protos_dot_planner__pb2.CreateUserPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
