FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV IN_CONTAINER 1

WORKDIR /app

RUN apt-get update
RUN pip install poetry

COPY pyproject.toml .
COPY poetry.lock .
COPY README.md .

RUN poetry install --no-interaction --no-root

COPY pyproject.toml .
COPY poetry.lock .
COPY README.md .
COPY clients/ ./clients/
COPY forms.py .
COPY config.py .
COPY utils/ ./utils
COPY protos/ ./protos/
COPY apps/api.py ./apps/
COPY db/ ./db/
COPY service/ ./service/
COPY tests/ ./tests/
COPY alembic/ ./alembic/
COPY alembic.ini .

ENTRYPOINT ["poetry", "run"]

#CMD ["poetry", "run", "alembic", "upgrade", "head"]
#CMD ["poetry", "run", "python", "observer_app.py"]