FROM python:3-alpine

WORKDIR /app

COPY pyproject.toml .
COPY poetry.lock .
COPY README.md .
COPY service/planner_service.py ./service/
COPY config.py .

COPY models/ ./models/
COPY protos/ ./protos/
COPY apps/planner_app.py ./apps/

RUN pip install poetry

# install psycopg2 dependencies
RUN apk update
RUN apk add postgresql-dev gcc python3-dev musl-dev


RUN poetry install --no-interaction --no-root


#CMD ["poetry", "run", "python", "planner_app.py"]