version: '4.0'
name: redis
services:
  postgres:
    image: postgres
    container_name: postgres_container
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: "qwerty"

  gateway:
    build:
      context: ../
      dockerfile: docker/Dockerfile.gateway
    image: gateway_image
    container_name: gateway_container
    networks:
      - internal
    env_file:
      - ../.env
    volumes:
      - ../apps:/app/apps
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: sh -c "poetry run uvicorn apps.api:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres
      - redis

  observer:
    build:
      context: ../
      dockerfile: docker/Dockerfile.observer
    image: observer_image
    container_name: observer_container
    networks:
      - internal
    env_file:
      - ../.env
    volumes:
      - ../apps:/app/apps
      - ../service:/app/service
    command:
      - sh -c "poetry run alembic upgrade head"
      - sh -c "poetry run python apps/observer_app.py"
    depends_on:
      - gateway

  redis:
    image: redis:6
    container_name: redis_container
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ../redis/data:/data
      - ../redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - "6379"
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf

networks:
  internal:
    driver: bridge