FROM python:3-alpine

WORKDIR /app

COPY pyproject.toml .
COPY poetry.lock .
RUN rm -rf
COPY README.md .
COPY service/auth_service.py ./service/
COPY config.py .
COPY db/ ./db/
COPY forms.py .
COPY utils/ ./utils/
COPY protos/ ./protos/
COPY apps/auth_app.py ./apps/

RUN pip install poetry

# install psycopg2 dependencies
RUN apk update
RUN apk add postgresql-dev gcc python3-dev musl-dev


RUN poetry install --no-interaction --no-root


#CMD ["poetry", "run", "python", "auth_app.py"]