FROM python:3-alpine

WORKDIR /app

COPY pyproject.toml .
COPY poetry.lock .
COPY README.md .
RUN pip install poetry

COPY config.py .
COPY db/ ./db/
COPY protos/ ./protos/
COPY apps/stats.py ./apps/


# install psycopg2 dependencies
RUN apk update
RUN apk add postgresql-dev gcc python3-dev musl-dev


RUN poetry install --no-interaction --no-root
