version: '4.0'
name: nginx
services:
  nginx:
    container_name: nginx_container
    image: nginx:latest
    networks:
      - internal
    volumes:
#      - type: bind
#        source: ../nginx/nginx.conf
#        target: /etc/nginx/conf.d/default.conf
#        read_only: true
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../cert.pem:/etc/nginx/conf/cert.pem
      - ../key.pem:/etc/nginx/conf/key.pem
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"

  gateway-1:
    build:
      context: ../
      dockerfile: docker/Dockerfile.gateway
    image: gateway_image
    container_name: gateway_container_1
    networks:
      - internal
    env_file:
      - ../.env
    environment:
      - MY_BACKEND_NAME=my-backend-1
    command: sh -c "poetry run uvicorn apps.api:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - nginx

  gateway-2:
    build:
      context: ../
      dockerfile: docker/Dockerfile.gateway
    image: gateway_image
    container_name: gateway_container_2
    networks:
      - internal
    env_file:
      - ../.env
    environment:
      - MY_BACKEND_NAME=my-backend-2
    command: sh -c "poetry run uvicorn apps.api:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - nginx

networks:
  internal:
    driver: bridge