FROM python:3-alpine

WORKDIR /app

COPY pyproject.toml .
COPY poetry.lock .
COPY README.md .
COPY clients/ ./clients/
COPY forms.py .
COPY config.py .

COPY utils/ ./utils
COPY protos/ ./protos/
COPY apps/api.py ./apps/

# install psycopg2 dependencies
RUN apk update
RUN apk add postgresql-dev gcc python3-dev musl-dev

RUN pip install poetry
RUN poetry install --no-interaction --no-root

#CMD ["poetry", "run", "uvicorn", "apps.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]